/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/vlad/Nim/lib -o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/main.o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/main.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#undef linux
#undef near
typedef struct SDLException_9c6o5Sg4WWFW32kxEqehq7A SDLException_9c6o5Sg4WWFW32kxEqehq7A;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct CellSeq_Axo1XVm9aaQueTOldv8le5w CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct GcHeap_1TRH1TZMaVZTnLNcIHuNFQ GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct GcStack_7fytPA5bBsob6See21YMRA GcStack_7fytPA5bBsob6See21YMRA;
typedef struct MemRegion_x81NhDv59b8ercDZ9bi85jyg MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct SmallChunk_tXn60W2f8h3jgAYdEmy5NQ SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct LLChunk_XsENErzHIZV9bhvyJx56wGw LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct BigChunk_Rv9c70Uhp2TytkX7eH78qEg BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct IntSet_EZObFrE3NC9bIb3YMkY9crZA IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct AvlNode_IaqjtwKhxLEpvDS9bct9blEw AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct TY_ujsjpB2O9cjj3uDHsXbnSzg TY_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct GcStat_0RwLoVBHZPfUAcLczmfQAg GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct CellSet_jG87P0AI9aZtss9ccTYBIISQ CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct PageDesc_fublkgIY4LG3mT51LU2WHg PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TSafePoint TSafePoint;
typedef struct WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
typedef struct GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw;
typedef struct PlayercolonObjectType__KotcRCluz2sG1d516JnnXw PlayercolonObjectType__KotcRCluz2sG1d516JnnXw;
typedef struct MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw;
typedef struct Vector2d_KzVBdX0o9c9aJpcyeuR3YopA Vector2d_KzVBdX0o9c9aJpcyeuR3YopA;
typedef struct TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct Point2d_eVNY8xahmVtt29cZz5fuKug Point2d_eVNY8xahmVtt29cZz5fuKug;
typedef struct TY_6H5Oh5UUvVCLiakt9aTwtUQ TY_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct ValueError_Gi06FkNeykJn7mrqRZYrkA ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Event_Uzh9aP43ffUpM9aa6vZvNEug Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ;
typedef struct KeySym_y3t7PyKCT9aYLDh9bLHT3UPw KeySym_y3t7PyKCT9aYLDh9bLHT3UPw;
typedef struct TY_TL9b2DXG9aysbx35PFbD8r0A TY_TL9b2DXG9aysbx35PFbD8r0A;
typedef struct TY_Ye8PLO8qqXk1tek2VP9c0UQ TY_Ye8PLO8qqXk1tek2VP9c0UQ;
typedef struct TY_rTI1z5tLuTbP9b133u2ve6A TY_rTI1z5tLuTbP9b133u2ve6A;
typedef struct BaseChunk_Sdq7WpT6qAH858F5ZEdG3w BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct FreeCell_u6M5LHprqzkn9axr04yg9bGQ FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NI32 SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  SDLException_9c6o5Sg4WWFW32kxEqehq7A  {
  Exception Sup;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, TY_09bvyvHFtWbkzL5AHgf0bKw) (void);
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  GcStack_7fytPA5bBsob6See21YMRA  {
void* bottom;
};
struct  CellSeq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  IntSet_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef AvlNode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  AvlNode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct TY_ujsjpB2O9cjj3uDHsXbnSzg {
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef TY_ujsjpB2O9cjj3uDHsXbnSzg TY_LzOv2eCDGiceMKQstCLmhw[30];
struct  HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg  {
NI len;
TY_LzOv2eCDGiceMKQstCLmhw chunks;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct  MemRegion_x81NhDv59b8ercDZ9bi85jyg  {
NI minLargeObj;
NI maxLargeObj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct  GcStat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct  CellSet_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
PageDesc_fublkgIY4LG3mT51LU2WHg* head;
PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  GcHeap_1TRH1TZMaVZTnLNcIHuNFQ  {
GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef long TY_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} TY_KeeAOYBd84Ofsw6Y7LizaQ;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CDECL_PTR(NIM_BOOL, TY_CS9bxA1KE4RHFQ1vMCkCBmg) (NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, TY_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg*, TY_eGPD9aEHv9b8sVQMCQaPsYkg) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window, int index, int flags);
typedef N_CDECL_PTR(int, TY_4hSZquf3VZZvlELaYshEWg) (int flags);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_BzAZji9bzvN1k9ae25rIlb8A) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef NIM_BOOL TY_1g2WNeJCsxcfiHzGd9aXXnw[6];
struct  Vector2d_KzVBdX0o9c9aJpcyeuR3YopA  {
NF x;
NF y;
};
struct  GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw  {
TY_1g2WNeJCsxcfiHzGd9aXXnw inputs;
RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
PlayercolonObjectType__KotcRCluz2sG1d516JnnXw* player;
MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw* map;
Vector2d_KzVBdX0o9c9aJpcyeuR3YopA camera;
};
struct  Point2d_eVNY8xahmVtt29cZz5fuKug  {
NF x;
NF y;
};
struct  PlayercolonObjectType__KotcRCluz2sG1d516JnnXw  {
TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture;
Point2d_eVNY8xahmVtt29cZz5fuKug pos;
Vector2d_KzVBdX0o9c9aJpcyeuR3YopA vel;
};
struct  MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw  {
TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture;
NI width;
NI height;
TY_6H5Oh5UUvVCLiakt9aTwtUQ* tiles;
};
typedef N_CDECL_PTR(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, TY_0icUM9coigCdz0HL3vd9bFCw) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NCSTRING file);
typedef NU8 FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct  ValueError_Gi06FkNeykJn7mrqRZYrkA  {
  Exception Sup;
};
typedef NU8 Input_s5Ob3tBofwvjEMag0EUt9bQ;
typedef NI32 EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 TY_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct  Event_Uzh9aP43ffUpM9aa6vZvNEug  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
TY_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
typedef NI32 Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(Bool32_lrv4aZgVTmBUYdrYUkLMlg, TY_b9aXpKFbsyZ0PIk3aYRVCAA) (Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef NI32 Scancode_ZC4j1APU9aAJPXuZfLFUG0w;
struct  KeySym_y3t7PyKCT9aYLDh9bLHT3UPw  {
Scancode_ZC4j1APU9aAJPXuZfLFUG0w scancode;
int sym;
NI16 modstate;
int unicode;
};
struct  KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ  {
EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
KeySym_y3t7PyKCT9aYLDh9bLHT3UPw keysym;
};
typedef N_CDECL_PTR(int, TY_zHpDbFN4o9bvP9cAphXAUHXg) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
struct TY_Ye8PLO8qqXk1tek2VP9c0UQ {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct TY_TL9b2DXG9aysbx35PFbD8r0A {
TY_Ye8PLO8qqXk1tek2VP9c0UQ Field0;
TY_Ye8PLO8qqXk1tek2VP9c0UQ Field1;
int Field2;
};
typedef TY_TL9b2DXG9aysbx35PFbD8r0A TY_jy4gD7At75vxH28XwwtPWQ[8];
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_uEPg0xGcL9ao0XgF3q7VnpA) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, TY_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, TY_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect, double angle, TY_rTI1z5tLuTbP9b133u2ve6A* center, int flip);
typedef N_CDECL_PTR(SDL_Return_8wc8or7UFANAtbisKJq7lw, TY_wbFMpEnGfJo5HTFBx413GA) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, TY_Ye8PLO8qqXk1tek2VP9c0UQ* srcrect, TY_Ye8PLO8qqXk1tek2VP9c0UQ* dstrect);
typedef N_CDECL_PTR(void, TY_9a8AalbnAaIxTUMpzQQqpjw) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, TY_T629bWTbvDFNyKAaO0BGGIQ) (WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevSize;
NI size;
};
struct  SmallChunk_tXn60W2f8h3jgAYdEmy5NQ  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct  LLChunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  BigChunk_Rv9c70Uhp2TytkX7eH78qEg  {
  BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  PageDesc_fublkgIY4LG3mT51LU2WHg  {
PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w  {
char dummy;
};
struct  RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg  {
char dummy;
};
struct  TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw  {
char dummy;
};
struct TY_rTI1z5tLuTbP9b133u2ve6A {
int Field0;
int Field1;
};
struct  FreeCell_u6M5LHprqzkn9axr04yg9bGQ  {
FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct TY_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_9cku33tvANHm87a2gL2qUHQ)(void);
N_NIMCALL(NIM_BOOL, toBool_9bg9codirrpaPKZJuSwGJgEg)(SDL_Return_8wc8or7UFANAtbisKJq7lw some);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_TY_T6kh3mQztDNb9bpesdVnfXw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(CellSeq_Axo1XVm9aaQueTOldv8le5w* s, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw*, newGame_zWVPUdYMMXsaDGDlr9b8jCg)(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer);
static N_NIMCALL(void, Marker_TY_YCTrfinh9avgj1XqcIjxy5g)(void* p, NI op);
static N_NIMCALL(void, Marker_TY_6H5Oh5UUvVCLiakt9aTwtUQ)(void* p, NI op);
static N_NIMCALL(void, Marker_TY_ocauRYs7mwvPMXNNtNuCvg)(void* p, NI op);
static N_NIMCALL(void, Marker_TY_9cyNkmaof4u5rxMpRhLO7ww)(void* p, NI op);
N_NIMCALL(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw*, newPlayer_BarZoqKN6nJJP9b8VGrYlLw)(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture);
N_NIMCALL(void, restartPlayer_QT7jvgv9cvJJXGHinw7kJYw)(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw* player);
static N_INLINE(Point2d_eVNY8xahmVtt29cZz5fuKug, point2d_4HtTb6DBuFYILwb7lqld9agbasic2d)(NF x, NF y);
static N_INLINE(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d)(NF x, NF y);
N_NIMCALL(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw*, newMap_jAu8ZC0IQxbLlCfm6oh9ciQ)(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, NimStringDesc* file);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(NIM_BOOL, readLine_sO1bQXVRA6RP9cdYJXNKeSw)(FILE* f, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NU, nsuParseUInt)(NimStringDesc* s);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(void, handleInput_cxDxsV8m9a9bI35ZS6LYEOkg)(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game);
N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
N_NIMCALL(Input_s5Ob3tBofwvjEMag0EUt9bQ, toInput_3ICDIvyyTTur09aCV3brbjw)(Scancode_ZC4j1APU9aAJPXuZfLFUG0w key);
N_NIMCALL(KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*, key_Sy9cYLza36NW1QN9asfW9a0LA)(Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
N_NIMCALL(void, physics_v4rgLvUfzuMKlKoARajx4g)(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwmain)(NF* x, NF y);
N_NIMCALL(NF, clamp_BGhQiHv5LFkg9aDgeidEq0g)(NF x, NF a, NF b);
static N_INLINE(void, pluseq__FhMmgV9c9csOjbyaRVR6fA3wmain)(Point2d_eVNY8xahmVtt29cZz5fuKug* p, Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(void, render_v4rgLvUfzuMKlKoARajx4g_2)(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game);
N_NIMCALL(void, renderTee_npLrEb1guLmePubRC189bKw)(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, Point2d_eVNY8xahmVtt29cZz5fuKug pos);
N_CDECL(TY_Ye8PLO8qqXk1tek2VP9c0UQ, rect_GH33Rh9bTnVBRLuu9bU7xoyA)(int x, int y, int w, int h);
static N_INLINE(Point2d_eVNY8xahmVtt29cZz5fuKug, minus__q81dFZGTLUb4p1FMszt1zAmain)(Point2d_eVNY8xahmVtt29cZz5fuKug p, Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(void, renderMap_Ku4lYikPFokb5sIoYqs2Lg)(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw* map, Vector2d_KzVBdX0o9c9aJpcyeuR3YopA camera);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qmain)(WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
extern TY_fvOXafK39cW5YZA9b9bzinu9cw Dl_148765_;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_9c6o5Sg4WWFW32kxEqehq7A_;
TNimType NTI_T6kh3mQztDNb9bpesdVnfXw_;
extern TY_09bvyvHFtWbkzL5AHgf0bKw Dl_149654_;
extern GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TY_CS9bxA1KE4RHFQ1vMCkCBmg Dl_150006_;
extern TY_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_149356_;
extern TY_eGPD9aEHv9b8sVQMCQaPsYkg Dl_148811_;
extern TY_4hSZquf3VZZvlELaYshEWg Dl_151604_;
extern TY_BzAZji9bzvN1k9ae25rIlb8A Dl_148617_;
TNimType NTI_AXKNUBcLNH5eN2Fv8Km0Gw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_1g2WNeJCsxcfiHzGd9aXXnw_;
extern TNimType NTI_7lSakCSU4VtJLR9aqvUx9buA_;
TNimType NTI_KotcRCluz2sG1d516JnnXw_;
extern TNimType NTI_X6TOzpP8PAev43Vu8HltPQ_;
extern TNimType NTI_eVNY8xahmVtt29cZz5fuKug_;
extern TNimType NTI_KzVBdX0o9c9aJpcyeuR3YopA_;
TNimType NTI_YCTrfinh9avgj1XqcIjxy5g_;
TNimType NTI_UhKL9bgn9bxVU2fd0O9coDPrw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_6H5Oh5UUvVCLiakt9aTwtUQ_;
TNimType NTI_ocauRYs7mwvPMXNNtNuCvg_;
TNimType NTI_9cyNkmaof4u5rxMpRhLO7ww_;
extern TY_0icUM9coigCdz0HL3vd9bFCw Dl_151621_;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
extern TY_b9aXpKFbsyZ0PIk3aYRVCAA Dl_149605_;
extern TY_zHpDbFN4o9bvP9cAphXAUHXg Dl_149017_;
extern TY_uEPg0xGcL9ao0XgF3q7VnpA Dl_148995_;
extern TY_wbFMpEnGfJo5HTFBx413GA Dl_148988_;
extern TY_9a8AalbnAaIxTUMpzQQqpjw Dl_149036_;
extern TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_151607_;
extern TY_9a8AalbnAaIxTUMpzQQqpjw Dl_148648_;
extern TY_T629bWTbvDFNyKAaO0BGGIQ Dl_149388_;
extern TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_148777_;
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_2, "SDL2 initialization failed", 26);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_3, ", SDL error: ", 13);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_5, "Linear texture filtering could not be enabled", 45);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_6, "Window could not be created", 27);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_9, "SDL2 Image initialization failed", 32);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_15, "Invalid value ", 14);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_16, " in map ", 8);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_17, "Incompatible line length in map ", 32);
STRING_LITERAL(TM_V45tF8B8NBcxFcjfe7lhBw_18, "default.map", 11);
static N_NIMCALL(void, Marker_TY_T6kh3mQztDNb9bpesdVnfXw)(void* p, NI op) {
	SDLException_9c6o5Sg4WWFW32kxEqehq7A* a;
	a = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}
static N_NIMCALL(void, Marker_TY_YCTrfinh9avgj1XqcIjxy5g)(void* p, NI op) {
	PlayercolonObjectType__KotcRCluz2sG1d516JnnXw* a;
	a = (PlayercolonObjectType__KotcRCluz2sG1d516JnnXw*)p;
}
static N_NIMCALL(void, Marker_TY_6H5Oh5UUvVCLiakt9aTwtUQ)(void* p, NI op) {
	TY_6H5Oh5UUvVCLiakt9aTwtUQ* a;
	NI T1_;
	a = (TY_6H5Oh5UUvVCLiakt9aTwtUQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	}
}
static N_NIMCALL(void, Marker_TY_ocauRYs7mwvPMXNNtNuCvg)(void* p, NI op) {
	MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw* a;
	a = (MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw*)p;
	nimGCvisit((void*)(*a).tiles, op);
}
static N_NIMCALL(void, Marker_TY_9cyNkmaof4u5rxMpRhLO7ww)(void* p, NI op) {
	GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* a;
	NI T1_;
	a = (GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 6; T1_++) {
	}
	nimGCvisit((void*)(*a).player, op);
	nimGCvisit((void*)(*a).map, op);
}

static N_INLINE(Point2d_eVNY8xahmVtt29cZz5fuKug, point2d_4HtTb6DBuFYILwb7lqld9agbasic2d)(NF x, NF y) {
	Point2d_eVNY8xahmVtt29cZz5fuKug result;
	result.x = x;
	result.y = y;
	return result;
}

static N_INLINE(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d)(NF x, NF y) {
	Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	result.x = x;
	result.y = y;
	return result;
}

N_NIMCALL(void, restartPlayer_QT7jvgv9cvJJXGHinw7kJYw)(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw* player) {
	(*player).pos = point2d_4HtTb6DBuFYILwb7lqld9agbasic2d(1.7000000000000000e+02, 5.0000000000000000e+02);
	(*player).vel = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(0.0, 0.0);
}

N_NIMCALL(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw*, newPlayer_BarZoqKN6nJJP9b8VGrYlLw)(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture) {
	PlayercolonObjectType__KotcRCluz2sG1d516JnnXw* result;
	result = (PlayercolonObjectType__KotcRCluz2sG1d516JnnXw*)0;
	result = (PlayercolonObjectType__KotcRCluz2sG1d516JnnXw*) newObj((&NTI_YCTrfinh9avgj1XqcIjxy5g_), sizeof(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw));
	(*result).texture = texture;
	restartPlayer_QT7jvgv9cvJJXGHinw7kJYw(result);
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

N_NIMCALL(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw*, newMap_jAu8ZC0IQxbLlCfm6oh9ciQ)(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, NimStringDesc* file) {
	MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw* result;
	result = (MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw*)0;
	result = (MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw*) newObj((&NTI_ocauRYs7mwvPMXNNtNuCvg_), sizeof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw));
	(*result).texture = texture;
	if ((*result).tiles) nimGCunrefNoCycle((*result).tiles);
	(*result).tiles = (TY_6H5Oh5UUvVCLiakt9aTwtUQ*) newSeqRC1((&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_), 0);
	{
		NimStringDesc* line;
		FILE* f;
		TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_14;
		line = (NimStringDesc*)0;
		f = open_hqzpWQbdA2B8l9a6wwNoP4g(file, ((FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) 8000));
		pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_14);
		TM_V45tF8B8NBcxFcjfe7lhBw_14.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_14.context);
		if (TM_V45tF8B8NBcxFcjfe7lhBw_14.status == 0) {
			NimStringDesc* res;
			res = rawNewString(((NI) 80));
			{
				while (1) {
					NIM_BOOL T5_;
					NI volatile width;
					T5_ = (NIM_BOOL)0;
					T5_ = readLine_sO1bQXVRA6RP9cdYJXNKeSw(f, (&res));
					if (!T5_) goto LA4;
					line = res;
					width = ((NI) 0);
					{
						NimStringDesc* word;
						NI volatile last;
						NI volatile splits;
						word = (NimStringDesc*)0;
						last = ((NI) 0);
						splits = ((NI) -1);
						{
							if (!(((NI) 0) < (line ? line->Sup.len : 0))) goto LA9_;
							{
								while (1) {
									NI first;
									if (!(last <= (line ? line->Sup.len : 0))) goto LA12;
									first = last;
									{
										while (1) {
											NIM_BOOL T15_;
											T15_ = (NIM_BOOL)0;
											T15_ = (last < (line ? line->Sup.len : 0));
											if (!(T15_)) goto LA16_;
											T15_ = !(((NU8)(line->data[last]) == (NU8)(32)));
											LA16_: ;
											if (!T15_) goto LA14;
											last += ((NI) 1);
										} LA14: ;
									}
									{
										if (!(splits == ((NI) 0))) goto LA19_;
										last = (line ? line->Sup.len : 0);
									}
									LA19_: ;
									word = copyStrLast(line, first, (NI)(last - ((NI) 1)));
									{
										NU value;
										{
											if (!((word) && (word)->Sup.len == 0)) goto LA24_;
											goto LA21;
										}
										LA24_: ;
										value = nsuParseUInt(word);
										{
											ValueError_Gi06FkNeykJn7mrqRZYrkA* volatile e;
											NimStringDesc* T30_;
											if (!((NU64)(((NU) 255)) < (NU64)(value))) goto LA28_;
											e = (ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
											e = (ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(ValueError_Gi06FkNeykJn7mrqRZYrkA));
											(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
											T30_ = (NimStringDesc*)0;
											T30_ = rawNewString(word->Sup.len + file->Sup.len + 22);
appendString(T30_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_15));
appendString(T30_, word);
appendString(T30_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_16));
appendString(T30_, file);
											asgnRefNoCycle((void**) (&(*e).Sup.message), T30_);
											asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
											raiseException((Exception*)e, "ValueError");
										}
										LA28_: ;
										(*result).tiles = (TY_6H5Oh5UUvVCLiakt9aTwtUQ*) incrSeqV2(&((*result).tiles)->Sup, sizeof(NU8));
										(*result).tiles->data[(*result).tiles->Sup.len] = ((NU8) (value));
										++(*result).tiles->Sup.len;
										width += ((NI) 1);
									} LA21: ;
									{
										if (!(splits == ((NI) 0))) goto LA33_;
										goto LA11;
									}
									LA33_: ;
									splits -= ((NI) 1);
									last += ((NI) 1);
								} LA12: ;
							} LA11: ;
						}
						LA9_: ;
					}
					{
						NIM_BOOL T37_;
						ValueError_Gi06FkNeykJn7mrqRZYrkA* volatile e_2;
						NimStringDesc* T41_;
						T37_ = (NIM_BOOL)0;
						T37_ = (((NI) 0) < (*result).width);
						if (!(T37_)) goto LA38_;
						T37_ = !(((*result).width == width));
						LA38_: ;
						if (!T37_) goto LA39_;
						e_2 = (ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
						e_2 = (ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(ValueError_Gi06FkNeykJn7mrqRZYrkA));
						(*e_2).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
						T41_ = (NimStringDesc*)0;
						T41_ = rawNewString(file->Sup.len + 32);
appendString(T41_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_17));
appendString(T41_, file);
						asgnRefNoCycle((void**) (&(*e_2).Sup.message), T41_);
						asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
						raiseException((Exception*)e_2, "ValueError");
					}
					LA39_: ;
					(*result).width = width;
					(*result).height += ((NI) 1);
				} LA4: ;
			}
			popSafePoint();
		}
		else {
			popSafePoint();
		}
		{
			close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
		}
		if (TM_V45tF8B8NBcxFcjfe7lhBw_14.status != 0) reraiseException();
	}
	return result;
}

N_NIMCALL(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw*, newGame_zWVPUdYMMXsaDGDlr9b8jCg)(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer) {
	GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* result;
	TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* T1_;
	TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* T2_;
	result = (GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw*)0;
	result = (GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw*) newObj((&NTI_9cyNkmaof4u5rxMpRhLO7ww_), sizeof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw));
	(*result).renderer = renderer;
	T1_ = (TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*)0;
	T1_ = Dl_151621_(renderer, "player.png");
	asgnRefNoCycle((void**) (&(*result).player), newPlayer_BarZoqKN6nJJP9b8VGrYlLw(T1_));
	T2_ = (TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*)0;
	T2_ = Dl_151621_(renderer, "grass.png");
	asgnRefNoCycle((void**) (&(*result).map), newMap_jAu8ZC0IQxbLlCfm6oh9ciQ(T2_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_18)));
	return result;
}

N_NIMCALL(Input_s5Ob3tBofwvjEMag0EUt9bQ, toInput_3ICDIvyyTTur09aCV3brbjw)(Scancode_ZC4j1APU9aAJPXuZfLFUG0w key) {
	Input_s5Ob3tBofwvjEMag0EUt9bQ result;
	result = (Input_s5Ob3tBofwvjEMag0EUt9bQ)0;
	switch (key) {
	case ((Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 4):
	{
		result = ((Input_s5Ob3tBofwvjEMag0EUt9bQ) 1);
	}
	break;
	case ((Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 7):
	{
		result = ((Input_s5Ob3tBofwvjEMag0EUt9bQ) 2);
	}
	break;
	case ((Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 44):
	{
		result = ((Input_s5Ob3tBofwvjEMag0EUt9bQ) 3);
	}
	break;
	case ((Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 21):
	{
		result = ((Input_s5Ob3tBofwvjEMag0EUt9bQ) 4);
	}
	break;
	case ((Scancode_ZC4j1APU9aAJPXuZfLFUG0w) 20):
	{
		result = ((Input_s5Ob3tBofwvjEMag0EUt9bQ) 5);
	}
	break;
	default:
	{
		result = ((Input_s5Ob3tBofwvjEMag0EUt9bQ) 0);
	}
	break;
	}
	return result;
}

N_NIMCALL(void, handleInput_cxDxsV8m9a9bI35ZS6LYEOkg)(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game) {
	Event_Uzh9aP43ffUpM9aa6vZvNEug event;
	event = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	{
		while (1) {
			Bool32_lrv4aZgVTmBUYdrYUkLMlg T3_;
			NIM_BOOL T4_;
			T3_ = (Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
			T3_ = Dl_149605_((&event));
			T4_ = (NIM_BOOL)0;
			T4_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T3_);
			if (!T4_) goto LA2;
			switch (event.kind) {
			case ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256):
			{
				(*game).inputs[(((Input_s5Ob3tBofwvjEMag0EUt9bQ) 5))- 0] = NIM_TRUE;
			}
			break;
			case ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 768):
			{
				KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ* T7_;
				Input_s5Ob3tBofwvjEMag0EUt9bQ T8_;
				T7_ = (KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*)0;
				T7_ = key_Sy9cYLza36NW1QN9asfW9a0LA((&event));
				T8_ = (Input_s5Ob3tBofwvjEMag0EUt9bQ)0;
				T8_ = toInput_3ICDIvyyTTur09aCV3brbjw((*T7_).keysym.scancode);
				(*game).inputs[(T8_)- 0] = NIM_TRUE;
			}
			break;
			case ((EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 769):
			{
				KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ* T10_;
				Input_s5Ob3tBofwvjEMag0EUt9bQ T11_;
				T10_ = (KeyboardEventObj_T9cLiQTAfT4u62zIltLlWzQ*)0;
				T10_ = key_Sy9cYLza36NW1QN9asfW9a0LA((&event));
				T11_ = (Input_s5Ob3tBofwvjEMag0EUt9bQ)0;
				T11_ = toInput_3ICDIvyyTTur09aCV3brbjw((*T10_).keysym.scancode);
				(*game).inputs[(T11_)- 0] = NIM_FALSE;
			}
			break;
			default:
			{
			}
			break;
			}
		} LA2: ;
	}
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwmain)(NF* x, NF y) {
	(*x) = ((NF)((*x)) + (NF)(y));
}

static N_INLINE(void, pluseq__FhMmgV9c9csOjbyaRVR6fA3wmain)(Point2d_eVNY8xahmVtt29cZz5fuKug* p, Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&(*p).x), v.x);
	pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&(*p).y), v.y);
}

N_NIMCALL(void, physics_v4rgLvUfzuMKlKoARajx4g)(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game) {
	NF direction;
	{
		if (!(*game).inputs[(((Input_s5Ob3tBofwvjEMag0EUt9bQ) 4))- 0]) goto LA3_;
		restartPlayer_QT7jvgv9cvJJXGHinw7kJYw((*game).player);
	}
	LA3_: ;
	{
		if (!(*game).inputs[(((Input_s5Ob3tBofwvjEMag0EUt9bQ) 3))- 0]) goto LA7_;
		(*(*game).player).vel.y = -2.1000000000000000e+01;
	}
	LA7_: ;
	direction = ((NF) ((NI)(((NI) ((*game).inputs[(((Input_s5Ob3tBofwvjEMag0EUt9bQ) 2))- 0])) - ((NI) ((*game).inputs[(((Input_s5Ob3tBofwvjEMag0EUt9bQ) 1))- 0])))));
	pluseq__7kHiltrvRlcg6wSYR3CxAwmain((&(*(*game).player).vel.y), 7.5000000000000000e-01);
	(*(*game).player).vel.x = clamp_BGhQiHv5LFkg9aDgeidEq0g(((NF)(((NF)(5.0000000000000000e-01) * (NF)((*(*game).player).vel.x))) + (NF)(((NF)(4.0000000000000000e+00) * (NF)(direction)))), -8.0000000000000000e+00, 8.0000000000000000e+00);
	pluseq__FhMmgV9c9csOjbyaRVR6fA3wmain((&(*(*game).player).pos), (*(*game).player).vel);
}

N_NIMCALL(void, renderTee_npLrEb1guLmePubRC189bKw)(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw* texture, Point2d_eVNY8xahmVtt29cZz5fuKug pos) {
	int x;
	int y;
	TY_jy4gD7At75vxH28XwwtPWQ bodyParts;
	x = ((int) (pos.x));
	y = ((int) (pos.y));
	memset((void*)bodyParts, 0, sizeof(bodyParts));
	bodyParts[0].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 192), ((int) 64), ((int) 64), ((int) 32));
	bodyParts[0].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 60)), y, ((int) 96), ((int) 48));
	bodyParts[0].Field2 = ((int) 0);
	bodyParts[1].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 96), ((int) 0), ((int) 96), ((int) 96));
	bodyParts[1].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 48)), (NI32)(y - ((NI32) 48)), ((int) 96), ((int) 96));
	bodyParts[1].Field2 = ((int) 0);
	bodyParts[2].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 192), ((int) 64), ((int) 64), ((int) 32));
	bodyParts[2].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 36)), y, ((int) 96), ((int) 48));
	bodyParts[2].Field2 = ((int) 0);
	bodyParts[3].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 192), ((int) 32), ((int) 64), ((int) 32));
	bodyParts[3].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 60)), y, ((int) 96), ((int) 48));
	bodyParts[3].Field2 = ((int) 0);
	bodyParts[4].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 0), ((int) 0), ((int) 96), ((int) 96));
	bodyParts[4].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 48)), (NI32)(y - ((NI32) 48)), ((int) 96), ((int) 96));
	bodyParts[4].Field2 = ((int) 0);
	bodyParts[5].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 192), ((int) 32), ((int) 64), ((int) 32));
	bodyParts[5].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 36)), y, ((int) 96), ((int) 48));
	bodyParts[5].Field2 = ((int) 0);
	bodyParts[6].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 64), ((int) 96), ((int) 32), ((int) 32));
	bodyParts[6].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 18)), (NI32)(y - ((NI32) 21)), ((int) 36), ((int) 36));
	bodyParts[6].Field2 = ((int) 0);
	bodyParts[7].Field0 = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 64), ((int) 96), ((int) 32), ((int) 32));
	bodyParts[7].Field1 = rect_GH33Rh9bTnVBRLuu9bU7xoyA((NI32)(x - ((NI32) 6)), (NI32)(y - ((NI32) 21)), ((int) 36), ((int) 36));
	bodyParts[7].Field2 = ((int) 1);
	{
		TY_TL9b2DXG9aysbx35PFbD8r0A* part;
		NI i;
		part = (TY_TL9b2DXG9aysbx35PFbD8r0A*)0;
		i = ((NI) 0);
		{
			if (!(((NI) (i)) <= ((NI) 7))) goto LA4_;
			{
				while (1) {
					SDL_Return_8wc8or7UFANAtbisKJq7lw T8_;
					part = (&bodyParts[(i)- 0]);
					T8_ = (SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
					T8_ = Dl_148995_(renderer, texture, (&(*part).Field0), (&(*part).Field1), 0.0, NIM_NIL, (*part).Field2);
					{
						if (!(((NI) 7) <= ((NI) (i)))) goto LA11_;
						goto LA6;
					}
					LA11_: ;
					i += ((NI) 1);
				}
			} LA6: ;
		}
		LA4_: ;
	}
}

static N_INLINE(Point2d_eVNY8xahmVtt29cZz5fuKug, minus__q81dFZGTLUb4p1FMszt1zAmain)(Point2d_eVNY8xahmVtt29cZz5fuKug p, Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	Point2d_eVNY8xahmVtt29cZz5fuKug result;
	result.x = ((NF)(p.x) - (NF)(v.x));
	result.y = ((NF)(p.y) - (NF)(v.y));
	return result;
}

N_NIMCALL(void, renderMap_Ku4lYikPFokb5sIoYqs2Lg)(RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw* map, Vector2d_KzVBdX0o9c9aJpcyeuR3YopA camera) {
	TY_Ye8PLO8qqXk1tek2VP9c0UQ clip;
	TY_Ye8PLO8qqXk1tek2VP9c0UQ dest;
	clip = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 0), ((int) 0), ((int) 64), ((int) 64));
	dest = rect_GH33Rh9bTnVBRLuu9bU7xoyA(((int) 0), ((int) 0), ((int) 64), ((int) 64));
	{
		NI i;
		NU8 tileNr;
		TY_6H5Oh5UUvVCLiakt9aTwtUQ* colontmp_;
		NI i_2;
		i = (NI)0;
		tileNr = (NU8)0;
		colontmp_ = (TY_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
		colontmp_ = (*map).tiles;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < (colontmp_ ? colontmp_->Sup.len : 0))) goto LA3;
				i = i_2;
				tileNr = colontmp_->data[i_2];
				{
					SDL_Return_8wc8or7UFANAtbisKJq7lw T9_;
					{
						if (!(tileNr == ((NI) 0))) goto LA7_;
						goto LA4;
					}
					LA7_: ;
					clip.Field0 = (NI32)(((int) ((NU8)((NU64)(tileNr) % (NU64)(((NI) 16))))) * ((int) 64));
					clip.Field1 = (NI32)(((int) ((NU8)((NU64)(tileNr) / (NU64)(((NI) 16))))) * ((int) 64));
					dest.Field0 = (NI32)((NI32)(((int) ((NI)(i % (*map).width))) * ((int) 64)) - ((int) (camera.x)));
					dest.Field1 = (NI32)((NI32)(((int) ((NI)(i / (*map).width))) * ((int) 64)) - ((int) (camera.y)));
					T9_ = (SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
					T9_ = Dl_148988_(renderer, (*map).texture, (&clip), (&dest));
				} LA4: ;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_NIMCALL(void, render_v4rgLvUfzuMKlKoARajx4g_2)(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game) {
	int T1_;
	Point2d_eVNY8xahmVtt29cZz5fuKug T2_;
	T1_ = (int)0;
	T1_ = Dl_149017_((*game).renderer);
	T2_ = minus__q81dFZGTLUb4p1FMszt1zAmain((*(*game).player).pos, (*game).camera);
	renderTee_npLrEb1guLmePubRC189bKw((*game).renderer, (*(*game).player).texture, T2_);
	renderMap_Ku4lYikPFokb5sIoYqs2Lg((*game).renderer, (*game).map, (*game).camera);
	Dl_149036_((*game).renderer);
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qmain)(WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	Dl_149388_(window);
}

N_NIMCALL(void, main_9cku33tvANHm87a2gL2qUHQ)(void) {
	TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_4;
	{
		SDL_Return_8wc8or7UFANAtbisKJq7lw T3_;
		NIM_BOOL T4_;
		SDLException_9c6o5Sg4WWFW32kxEqehq7A* e;
		NimStringDesc* T7_;
		NCSTRING T8_;
		NimStringDesc* T9_;
		T3_ = (SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
		T3_ = Dl_148765_(((int) 16417));
		T4_ = (NIM_BOOL)0;
		T4_ = toBool_9bg9codirrpaPKZJuSwGJgEg(T3_);
		if (!!(T4_)) goto LA5_;
		e = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
		e = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A));
		(*e).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
		T7_ = (NimStringDesc*)0;
		T8_ = (NCSTRING)0;
		T8_ = Dl_149654_();
		T9_ = (NimStringDesc*)0;
		T9_ = cstrToNimstr(T8_);
		T7_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_2)->Sup.len + T9_->Sup.len + 13);
appendString(T7_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_2));
appendString(T7_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_3));
appendString(T7_, T9_);
		asgnRefNoCycle((void**) (&(*e).Sup.message), T7_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "SDLException");
	}
	LA5_: ;
	pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_4);
	TM_V45tF8B8NBcxFcjfe7lhBw_4.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_4.context);
	if (TM_V45tF8B8NBcxFcjfe7lhBw_4.status == 0) {
		WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window;
		TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_7;
		{
			NIM_BOOL T13_;
			SDLException_9c6o5Sg4WWFW32kxEqehq7A* volatile e_2;
			NimStringDesc* T16_;
			NCSTRING T17_;
			NimStringDesc* T18_;
			T13_ = (NIM_BOOL)0;
			T13_ = Dl_150006_("SDL_RENDER_SCALE_QUALITY", "2");
			if (!!(T13_)) goto LA14_;
			e_2 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
			e_2 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A));
			(*e_2).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
			T16_ = (NimStringDesc*)0;
			T17_ = (NCSTRING)0;
			T17_ = Dl_149654_();
			T18_ = (NimStringDesc*)0;
			T18_ = cstrToNimstr(T17_);
			T16_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_5)->Sup.len + T18_->Sup.len + 13);
appendString(T16_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_5));
appendString(T16_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_3));
appendString(T16_, T18_);
			asgnRefNoCycle((void**) (&(*e_2).Sup.message), T16_);
			asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
			raiseException((Exception*)e_2, "SDLException");
		}
		LA14_: ;
		window = Dl_149356_("Our own 2D platformer", ((int) 805240832), ((int) 805240832), ((int) 1280), ((int) 720), ((unsigned int) 4));
		{
			SDLException_9c6o5Sg4WWFW32kxEqehq7A* volatile e_3;
			NimStringDesc* T23_;
			NCSTRING T24_;
			NimStringDesc* T25_;
			if (!(window == 0)) goto LA21_;
			e_3 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
			e_3 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A));
			(*e_3).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
			T23_ = (NimStringDesc*)0;
			T24_ = (NCSTRING)0;
			T24_ = Dl_149654_();
			T25_ = (NimStringDesc*)0;
			T25_ = cstrToNimstr(T24_);
			T23_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_6)->Sup.len + T25_->Sup.len + 13);
appendString(T23_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_6));
appendString(T23_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_3));
appendString(T23_, T25_);
			asgnRefNoCycle((void**) (&(*e_3).Sup.message), T23_);
			asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
			raiseException((Exception*)e_3, "SDLException");
		}
		LA21_: ;
		pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_7);
		TM_V45tF8B8NBcxFcjfe7lhBw_7.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_7.context);
		if (TM_V45tF8B8NBcxFcjfe7lhBw_7.status == 0) {
			RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer;
			TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_8;
			renderer = Dl_148811_(window, ((int) 1), ((NI32) 6));
			{
				SDLException_9c6o5Sg4WWFW32kxEqehq7A* volatile e_4;
				NimStringDesc* T31_;
				NCSTRING T32_;
				NimStringDesc* T33_;
				if (!(renderer == 0)) goto LA29_;
				e_4 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
				e_4 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A));
				(*e_4).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
				T31_ = (NimStringDesc*)0;
				T32_ = (NCSTRING)0;
				T32_ = Dl_149654_();
				T33_ = (NimStringDesc*)0;
				T33_ = cstrToNimstr(T32_);
				T31_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_6)->Sup.len + T33_->Sup.len + 13);
appendString(T31_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_6));
appendString(T31_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_3));
appendString(T31_, T33_);
				asgnRefNoCycle((void**) (&(*e_4).Sup.message), T31_);
				asgnRef((void**) (&(*e_4).Sup.parent), NIM_NIL);
				raiseException((Exception*)e_4, "SDLException");
			}
			LA29_: ;
			pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_8);
			TM_V45tF8B8NBcxFcjfe7lhBw_8.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_8.context);
			if (TM_V45tF8B8NBcxFcjfe7lhBw_8.status == 0) {
				TSafePoint TM_V45tF8B8NBcxFcjfe7lhBw_10;
				{
					int T37_;
					SDLException_9c6o5Sg4WWFW32kxEqehq7A* volatile e_5;
					NimStringDesc* T40_;
					NCSTRING T41_;
					NimStringDesc* T42_;
					T37_ = (int)0;
					T37_ = Dl_151604_(((int) 2));
					if (!!((T37_ == ((int) 2)))) goto LA38_;
					e_5 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*)0;
					e_5 = (SDLException_9c6o5Sg4WWFW32kxEqehq7A*) newObj((&NTI_T6kh3mQztDNb9bpesdVnfXw_), sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A));
					(*e_5).Sup.Sup.m_type = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
					T40_ = (NimStringDesc*)0;
					T41_ = (NCSTRING)0;
					T41_ = Dl_149654_();
					T42_ = (NimStringDesc*)0;
					T42_ = cstrToNimstr(T41_);
					T40_ = rawNewString(((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_9)->Sup.len + T42_->Sup.len + 13);
appendString(T40_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_9));
appendString(T40_, ((NimStringDesc*) &TM_V45tF8B8NBcxFcjfe7lhBw_3));
appendString(T40_, T42_);
					asgnRefNoCycle((void**) (&(*e_5).Sup.message), T40_);
					asgnRef((void**) (&(*e_5).Sup.parent), NIM_NIL);
					raiseException((Exception*)e_5, "SDLException");
				}
				LA38_: ;
				pushSafePoint(&TM_V45tF8B8NBcxFcjfe7lhBw_10);
				TM_V45tF8B8NBcxFcjfe7lhBw_10.status = setjmp(TM_V45tF8B8NBcxFcjfe7lhBw_10.context);
				if (TM_V45tF8B8NBcxFcjfe7lhBw_10.status == 0) {
					SDL_Return_8wc8or7UFANAtbisKJq7lw T44_;
					GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw* game;
					NF startTime;
					NI volatile lastTick;
					T44_ = (SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
					T44_ = Dl_148617_(renderer, ((NU8) 110), ((NU8) 132), ((NU8) 174), ((NU8) 255));
					game = newGame_zWVPUdYMMXsaDGDlr9b8jCg(renderer);
					startTime = ntepochTime();
					lastTick = ((NI) 0);
					{
						while (1) {
							NI newTick;
							NF T47_;
							if (!!((*game).inputs[(((Input_s5Ob3tBofwvjEMag0EUt9bQ) 5))- 0])) goto LA46;
							handleInput_cxDxsV8m9a9bI35ZS6LYEOkg(game);
							T47_ = (NF)0;
							T47_ = ntepochTime();
							newTick = ((NI) (((NF)(((NF)(T47_) - (NF)(startTime))) * (NF)(5.0000000000000000e+01))));
							{
								NI tick;
								NI colontmp_;
								NI volatile res;
								tick = (NI)0;
								colontmp_ = (NI)0;
								colontmp_ = (NI)(lastTick + ((NI) 1));
								res = colontmp_;
								{
									while (1) {
										if (!(res <= newTick)) goto LA50;
										tick = res;
										physics_v4rgLvUfzuMKlKoARajx4g(game);
										res += ((NI) 1);
									} LA50: ;
								}
							}
							lastTick = newTick;
							render_v4rgLvUfzuMKlKoARajx4g_2(game);
						} LA46: ;
					}
					popSafePoint();
				}
				else {
					popSafePoint();
				}
				{
					Dl_151607_();
				}
				if (TM_V45tF8B8NBcxFcjfe7lhBw_10.status != 0) reraiseException();
				popSafePoint();
			}
			else {
				popSafePoint();
			}
			{
				Dl_148648_(renderer);
			}
			if (TM_V45tF8B8NBcxFcjfe7lhBw_8.status != 0) reraiseException();
			popSafePoint();
		}
		else {
			popSafePoint();
		}
		{
			destroy_sFvfWODyHxg46OuBtGyU8Qmain(window);
		}
		if (TM_V45tF8B8NBcxFcjfe7lhBw_7.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		Dl_148777_();
	}
	if (TM_V45tF8B8NBcxFcjfe7lhBw_4.status != 0) reraiseException();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_basic2dDatInit000();
	stdlib_timesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_imageDatInit000();
	mainDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_basic2dInit000();
	stdlib_timesInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	sdl2_sdl2Init000();
	sdl2_imageInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	main_9cku33tvANHm87a2gL2qUHQ();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
static TNimNode* TM_V45tF8B8NBcxFcjfe7lhBw_11[5];
static TNimNode* TM_V45tF8B8NBcxFcjfe7lhBw_12[3];
static TNimNode* TM_V45tF8B8NBcxFcjfe7lhBw_13[4];
static TNimNode TM_V45tF8B8NBcxFcjfe7lhBw_0[16];
NTI_9c6o5Sg4WWFW32kxEqehq7A_.size = sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A);
NTI_9c6o5Sg4WWFW32kxEqehq7A_.kind = 17;
NTI_9c6o5Sg4WWFW32kxEqehq7A_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[0].len = 0; TM_V45tF8B8NBcxFcjfe7lhBw_0[0].kind = 2;
NTI_9c6o5Sg4WWFW32kxEqehq7A_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[0];
NTI_T6kh3mQztDNb9bpesdVnfXw_.size = sizeof(SDLException_9c6o5Sg4WWFW32kxEqehq7A*);
NTI_T6kh3mQztDNb9bpesdVnfXw_.kind = 22;
NTI_T6kh3mQztDNb9bpesdVnfXw_.base = (&NTI_9c6o5Sg4WWFW32kxEqehq7A_);
NTI_T6kh3mQztDNb9bpesdVnfXw_.marker = Marker_TY_T6kh3mQztDNb9bpesdVnfXw;
NTI_AXKNUBcLNH5eN2Fv8Km0Gw_.size = sizeof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw);
NTI_AXKNUBcLNH5eN2Fv8Km0Gw_.kind = 18;
NTI_AXKNUBcLNH5eN2Fv8Km0Gw_.base = 0;
NTI_AXKNUBcLNH5eN2Fv8Km0Gw_.flags = 2;
TM_V45tF8B8NBcxFcjfe7lhBw_11[0] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[2];
NTI_1g2WNeJCsxcfiHzGd9aXXnw_.size = sizeof(TY_1g2WNeJCsxcfiHzGd9aXXnw);
NTI_1g2WNeJCsxcfiHzGd9aXXnw_.kind = 16;
NTI_1g2WNeJCsxcfiHzGd9aXXnw_.base = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
NTI_1g2WNeJCsxcfiHzGd9aXXnw_.flags = 3;
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].offset = offsetof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw, inputs);
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].typ = (&NTI_1g2WNeJCsxcfiHzGd9aXXnw_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[2].name = "inputs";
TM_V45tF8B8NBcxFcjfe7lhBw_11[1] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[3];
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].offset = offsetof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw, renderer);
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].typ = (&NTI_7lSakCSU4VtJLR9aqvUx9buA_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[3].name = "renderer";
TM_V45tF8B8NBcxFcjfe7lhBw_11[2] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[4];
NTI_KotcRCluz2sG1d516JnnXw_.size = sizeof(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw);
NTI_KotcRCluz2sG1d516JnnXw_.kind = 18;
NTI_KotcRCluz2sG1d516JnnXw_.base = 0;
NTI_KotcRCluz2sG1d516JnnXw_.flags = 3;
TM_V45tF8B8NBcxFcjfe7lhBw_12[0] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[6];
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].offset = offsetof(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw, texture);
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].typ = (&NTI_X6TOzpP8PAev43Vu8HltPQ_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[6].name = "texture";
TM_V45tF8B8NBcxFcjfe7lhBw_12[1] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[7];
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].offset = offsetof(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw, pos);
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].typ = (&NTI_eVNY8xahmVtt29cZz5fuKug_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[7].name = "pos";
TM_V45tF8B8NBcxFcjfe7lhBw_12[2] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[8];
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].offset = offsetof(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw, vel);
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].typ = (&NTI_KzVBdX0o9c9aJpcyeuR3YopA_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[8].name = "vel";
TM_V45tF8B8NBcxFcjfe7lhBw_0[5].len = 3; TM_V45tF8B8NBcxFcjfe7lhBw_0[5].kind = 2; TM_V45tF8B8NBcxFcjfe7lhBw_0[5].sons = &TM_V45tF8B8NBcxFcjfe7lhBw_12[0];
NTI_KotcRCluz2sG1d516JnnXw_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[5];
NTI_YCTrfinh9avgj1XqcIjxy5g_.size = sizeof(PlayercolonObjectType__KotcRCluz2sG1d516JnnXw*);
NTI_YCTrfinh9avgj1XqcIjxy5g_.kind = 22;
NTI_YCTrfinh9avgj1XqcIjxy5g_.base = (&NTI_KotcRCluz2sG1d516JnnXw_);
NTI_YCTrfinh9avgj1XqcIjxy5g_.flags = 2;
NTI_YCTrfinh9avgj1XqcIjxy5g_.marker = Marker_TY_YCTrfinh9avgj1XqcIjxy5g;
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].offset = offsetof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw, player);
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].typ = (&NTI_YCTrfinh9avgj1XqcIjxy5g_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[4].name = "player";
TM_V45tF8B8NBcxFcjfe7lhBw_11[3] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[9];
NTI_UhKL9bgn9bxVU2fd0O9coDPrw_.size = sizeof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw);
NTI_UhKL9bgn9bxVU2fd0O9coDPrw_.kind = 18;
NTI_UhKL9bgn9bxVU2fd0O9coDPrw_.base = 0;
NTI_UhKL9bgn9bxVU2fd0O9coDPrw_.flags = 2;
TM_V45tF8B8NBcxFcjfe7lhBw_13[0] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[11];
TM_V45tF8B8NBcxFcjfe7lhBw_0[11].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[11].offset = offsetof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw, texture);
TM_V45tF8B8NBcxFcjfe7lhBw_0[11].typ = (&NTI_X6TOzpP8PAev43Vu8HltPQ_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[11].name = "texture";
TM_V45tF8B8NBcxFcjfe7lhBw_13[1] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[12];
TM_V45tF8B8NBcxFcjfe7lhBw_0[12].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[12].offset = offsetof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw, width);
TM_V45tF8B8NBcxFcjfe7lhBw_0[12].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[12].name = "width";
TM_V45tF8B8NBcxFcjfe7lhBw_13[2] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[13];
TM_V45tF8B8NBcxFcjfe7lhBw_0[13].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[13].offset = offsetof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw, height);
TM_V45tF8B8NBcxFcjfe7lhBw_0[13].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[13].name = "height";
TM_V45tF8B8NBcxFcjfe7lhBw_13[3] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[14];
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.size = sizeof(TY_6H5Oh5UUvVCLiakt9aTwtUQ*);
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.kind = 24;
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.flags = 2;
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.marker = Marker_TY_6H5Oh5UUvVCLiakt9aTwtUQ;
TM_V45tF8B8NBcxFcjfe7lhBw_0[14].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[14].offset = offsetof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw, tiles);
TM_V45tF8B8NBcxFcjfe7lhBw_0[14].typ = (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[14].name = "tiles";
TM_V45tF8B8NBcxFcjfe7lhBw_0[10].len = 4; TM_V45tF8B8NBcxFcjfe7lhBw_0[10].kind = 2; TM_V45tF8B8NBcxFcjfe7lhBw_0[10].sons = &TM_V45tF8B8NBcxFcjfe7lhBw_13[0];
NTI_UhKL9bgn9bxVU2fd0O9coDPrw_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[10];
NTI_ocauRYs7mwvPMXNNtNuCvg_.size = sizeof(MapcolonObjectType__UhKL9bgn9bxVU2fd0O9coDPrw*);
NTI_ocauRYs7mwvPMXNNtNuCvg_.kind = 22;
NTI_ocauRYs7mwvPMXNNtNuCvg_.base = (&NTI_UhKL9bgn9bxVU2fd0O9coDPrw_);
NTI_ocauRYs7mwvPMXNNtNuCvg_.flags = 2;
NTI_ocauRYs7mwvPMXNNtNuCvg_.marker = Marker_TY_ocauRYs7mwvPMXNNtNuCvg;
TM_V45tF8B8NBcxFcjfe7lhBw_0[9].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[9].offset = offsetof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw, map);
TM_V45tF8B8NBcxFcjfe7lhBw_0[9].typ = (&NTI_ocauRYs7mwvPMXNNtNuCvg_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[9].name = "map";
TM_V45tF8B8NBcxFcjfe7lhBw_11[4] = &TM_V45tF8B8NBcxFcjfe7lhBw_0[15];
TM_V45tF8B8NBcxFcjfe7lhBw_0[15].kind = 1;
TM_V45tF8B8NBcxFcjfe7lhBw_0[15].offset = offsetof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw, camera);
TM_V45tF8B8NBcxFcjfe7lhBw_0[15].typ = (&NTI_KzVBdX0o9c9aJpcyeuR3YopA_);
TM_V45tF8B8NBcxFcjfe7lhBw_0[15].name = "camera";
TM_V45tF8B8NBcxFcjfe7lhBw_0[1].len = 5; TM_V45tF8B8NBcxFcjfe7lhBw_0[1].kind = 2; TM_V45tF8B8NBcxFcjfe7lhBw_0[1].sons = &TM_V45tF8B8NBcxFcjfe7lhBw_11[0];
NTI_AXKNUBcLNH5eN2Fv8Km0Gw_.node = &TM_V45tF8B8NBcxFcjfe7lhBw_0[1];
NTI_9cyNkmaof4u5rxMpRhLO7ww_.size = sizeof(GamecolonObjectType__AXKNUBcLNH5eN2Fv8Km0Gw*);
NTI_9cyNkmaof4u5rxMpRhLO7ww_.kind = 22;
NTI_9cyNkmaof4u5rxMpRhLO7ww_.base = (&NTI_AXKNUBcLNH5eN2Fv8Km0Gw_);
NTI_9cyNkmaof4u5rxMpRhLO7ww_.flags = 2;
NTI_9cyNkmaof4u5rxMpRhLO7ww_.marker = Marker_TY_9cyNkmaof4u5rxMpRhLO7ww;
}

