/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/vlad/Nim/lib -o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/sdl2_image.o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/sdl2_image.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw;
typedef struct RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY_4hSZquf3VZZvlELaYshEWg) (int flags);
typedef N_CDECL_PTR(TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw*, TY_0icUM9coigCdz0HL3vd9bFCw) (RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg* renderer, NCSTRING file);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct  TexturePtrcolonObjectType__6n0oqQPDsaMFNhtiJ29bOXw  {
char dummy;
};
struct  RendererPtrcolonObjectType__RZ5I89cPVLRdJchBQYVCSfg  {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static void* TM_EK6wIoNHNycCv1LJkkuJvw_2;
TY_4hSZquf3VZZvlELaYshEWg Dl_151604_;
TY_0icUM9coigCdz0HL3vd9bFCw Dl_151621_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_151607_;
STRING_LITERAL(TM_EK6wIoNHNycCv1LJkkuJvw_4, "libSDL2_image.so", 16);
STRING_LITERAL(TM_EK6wIoNHNycCv1LJkkuJvw_6, "libSDL2_image.so.0", 18);
STRING_LITERAL(TM_EK6wIoNHNycCv1LJkkuJvw_8, "libSDL2_image-2.0.so", 20);
STRING_LITERAL(TM_EK6wIoNHNycCv1LJkkuJvw_10, "libSDL2_image-2.0.so.0", 22);
STRING_LITERAL(TM_EK6wIoNHNycCv1LJkkuJvw_11, "libSDL2_image(|-2.0).so(|.0)", 28);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void) {
if (!((TM_EK6wIoNHNycCv1LJkkuJvw_2 = nimLoadLibrary((NimStringDesc*) &TM_EK6wIoNHNycCv1LJkkuJvw_4))
||(TM_EK6wIoNHNycCv1LJkkuJvw_2 = nimLoadLibrary((NimStringDesc*) &TM_EK6wIoNHNycCv1LJkkuJvw_6))
||(TM_EK6wIoNHNycCv1LJkkuJvw_2 = nimLoadLibrary((NimStringDesc*) &TM_EK6wIoNHNycCv1LJkkuJvw_8))
||(TM_EK6wIoNHNycCv1LJkkuJvw_2 = nimLoadLibrary((NimStringDesc*) &TM_EK6wIoNHNycCv1LJkkuJvw_10))
)) nimLoadLibraryError((NimStringDesc*) &TM_EK6wIoNHNycCv1LJkkuJvw_11);
	Dl_151604_ = (TY_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_EK6wIoNHNycCv1LJkkuJvw_2, "IMG_Init");
	Dl_151621_ = (TY_0icUM9coigCdz0HL3vd9bFCw) nimGetProcAddr(TM_EK6wIoNHNycCv1LJkkuJvw_2, "IMG_LoadTexture");
	Dl_151607_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_EK6wIoNHNycCv1LJkkuJvw_2, "IMG_Quit");
}

