/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/vlad/Nim/lib -o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/sdl2_nim_sdl.o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/sdl2_nim_sdl.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, TY_qLs9bEMEYHZYOeFIf1LOpoQ) (NU32 flags);
typedef N_CDECL_PTR(NCSTRING, TY_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(void*, TY_hKarI59cLAeI0v1WuQhCZ9ag) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(void*, TY_jPHHnsvDYo8Q3NQemQIGWg) (void* window, int index, NU32 flags);
typedef N_CDECL_PTR(int, TY_buOIiiD42E5nxpbw32t0bA) (void* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(void, TY_32w2ZypAyMWuajvi2Jt79cg) (void* renderer);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef N_CDECL_PTR(int, TY_fbYpjfe38x3ujjAmVRbI1Q) (void* renderer);
typedef N_CDECL_PTR(void, TY_CGFSM2Hc7U0HyNmEEh3xng) (NU32 ms);
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_T8sPUeYymAg4VnmycaqyjQ_2;
TY_qLs9bEMEYHZYOeFIf1LOpoQ Dl_105420_;
TY_09bvyvHFtWbkzL5AHgf0bKw Dl_106445_;
TY_hKarI59cLAeI0v1WuQhCZ9ag Dl_110046_;
TY_jPHHnsvDYo8Q3NQemQIGWg Dl_113323_;
TY_buOIiiD42E5nxpbw32t0bA Dl_113506_;
TY_32w2ZypAyMWuajvi2Jt79cg Dl_113624_;
TY_32w2ZypAyMWuajvi2Jt79cg Dl_110268_;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_105432_;
TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TY_fbYpjfe38x3ujjAmVRbI1Q Dl_113541_;
TY_32w2ZypAyMWuajvi2Jt79cg Dl_113618_;
TY_CGFSM2Hc7U0HyNmEEh3xng Dl_114246_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_4, "libSDL2.so", 10);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_6, "libSDL2.so.0.4.1", 16);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_8, "libSDL2.so.0", 12);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_10, "libSDL2-2.0.so", 14);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_12, "libSDL2-2.0.so.0.4.1", 20);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_14, "libSDL2-2.0.so.0", 16);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_15, "libSDL2(|-2.0).so(|.0.4.1|.0)", 29);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdlInit000)(void) {
	nimfr_("sdl", "sdl.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdlDatInit000)(void) {
NTI_vr5DoT1jILTGdRlYv1OYpw_.size = sizeof(void*);
NTI_vr5DoT1jILTGdRlYv1OYpw_.kind = 26;
NTI_vr5DoT1jILTGdRlYv1OYpw_.base = 0;
NTI_vr5DoT1jILTGdRlYv1OYpw_.flags = 3;
if (!((TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_4))
||(TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_6))
||(TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_8))
||(TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_10))
||(TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_12))
||(TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_14))
)) nimLoadLibraryError((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_15);
	Dl_105420_ = (TY_qLs9bEMEYHZYOeFIf1LOpoQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_Init");
	Dl_106445_ = (TY_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetError");
	Dl_110046_ = (TY_hKarI59cLAeI0v1WuQhCZ9ag) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_CreateWindow");
	Dl_113323_ = (TY_jPHHnsvDYo8Q3NQemQIGWg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_CreateRenderer");
	Dl_113506_ = (TY_buOIiiD42E5nxpbw32t0bA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetRenderDrawColor");
	Dl_113624_ = (TY_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_DestroyRenderer");
	Dl_110268_ = (TY_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_DestroyWindow");
	Dl_105432_ = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_Quit");
	Dl_113541_ = (TY_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderClear");
	Dl_113618_ = (TY_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderPresent");
	Dl_114246_ = (TY_CGFSM2Hc7U0HyNmEEh3xng) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_Delay");
}

