/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/vlad/Nim/lib -o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/stdlib_parseutils.o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/stdlib_parseutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, npuParseBiggestUInt)(NimStringDesc* s, NU64* number, NI start);
N_NIMCALL(NI, rawParseUInt_OzYQCLjNwotWpNl0Q1C9cmQ)(NimStringDesc* s, NU64* b, NI start);

N_NIMCALL(NI, rawParseUInt_OzYQCLjNwotWpNl0Q1C9cmQ)(NimStringDesc* s, NU64* b, NI start) {
	NI result;
	NU64 res;
	NU64 prev;
	NI i;
{	result = (NI)0;
	res = 0ULL;
	prev = 0ULL;
	i = start;
	{
		if (!((NU8)(s->data[i]) == (NU8)(43))) goto LA3_;
		i += ((NI) 1);
	}
	LA3_: ;
	{
		if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA7_;
		(*b) = 0ULL;
		{
			while (1) {
				if (!(((NU8)(s->data[i])) >= ((NU8)(48)) && ((NU8)(s->data[i])) <= ((NU8)(57)))) goto LA10;
				prev = res;
				res = (NU64)((NU64)((NU64)((NU64)(res) * (NU64)(((NI) 10)))) + (NU64)(((NU64) ((NI)(((NI) (((NU8)(s->data[i])))) - ((NI) 48))))));
				{
					if (!((NU64)(res) < (NU64)(prev))) goto LA13_;
					result = ((NI) 0);
					goto BeforeRet_;
				}
				LA13_: ;
				i += ((NI) 1);
				{
					while (1) {
						if (!((NU8)(s->data[i]) == (NU8)(95))) goto LA16;
						i += ((NI) 1);
					} LA16: ;
				}
			} LA10: ;
		}
		(*b) = res;
		result = (NI)(i - start);
	}
	LA7_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NI, npuParseBiggestUInt)(NimStringDesc* s, NU64* number, NI start) {
	NI result;
	NU64 res;
	result = (NI)0;
	res = (NU64)0;
	result = rawParseUInt_OzYQCLjNwotWpNl0Q1C9cmQ(s, (&res), start);
	(*number) = res;
	return result;
}

N_NIMCALL(NI, npuParseUInt)(NimStringDesc* s, NU* number, NI start) {
	NI result;
	NU64 res;
	result = (NI)0;
	res = (NU64)0;
	result = npuParseBiggestUInt(s, (&res), start);
	{
		if (!!((result == ((NI) 0)))) goto LA3_;
		(*number) = ((NU) (res));
	}
	LA3_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

