/* Generated by Nim Compiler v0.17.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/vlad/Nim/lib -o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/stdlib_basic2d.o /home/vlad/Experiments/computer_graphics/software_renderers/src/nimcache/stdlib_basic2d.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
#undef near
typedef struct Matrix2d_apt8v8Iw9bh7km28IcOJIkg Matrix2d_apt8v8Iw9bh7km28IcOJIkg;
typedef struct Point2d_eVNY8xahmVtt29cZz5fuKug Point2d_eVNY8xahmVtt29cZz5fuKug;
typedef struct Vector2d_KzVBdX0o9c9aJpcyeuR3YopA Vector2d_KzVBdX0o9c9aJpcyeuR3YopA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  Matrix2d_apt8v8Iw9bh7km28IcOJIkg  {
NF ax;
NF ay;
NF bx;
NF by;
NF tx;
NF ty;
};
struct  Point2d_eVNY8xahmVtt29cZz5fuKug  {
NF x;
NF y;
};
struct  Vector2d_KzVBdX0o9c9aJpcyeuR3YopA  {
NF x;
NF y;
};
typedef NU8 TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct  TNimType  {
NI size;
TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(Matrix2d_apt8v8Iw9bh7km28IcOJIkg, matrix2d_ZkrhJTvT5qdZLXWIJxuuVw)(NF ax, NF ay, NF bx, NF by, NF tx, NF ty);
static N_INLINE(void, setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d)(Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t, NF ax, NF ay, NF bx, NF by, NF tx, NF ty);
static N_INLINE(Point2d_eVNY8xahmVtt29cZz5fuKug, point2d_4HtTb6DBuFYILwb7lqld9agbasic2d)(NF x, NF y);
static N_INLINE(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d)(NF x, NF y);
Matrix2d_apt8v8Iw9bh7km28IcOJIkg IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g;
Point2d_eVNY8xahmVtt29cZz5fuKug ORIGO_fcPFYT9cYuzJZVhuTlBCWIA;
Vector2d_KzVBdX0o9c9aJpcyeuR3YopA XAXIS_cHisHYvnFnWkQFsXQwR8LA;
Vector2d_KzVBdX0o9c9aJpcyeuR3YopA YAXIS_Tg25xvoRc1btSr7LczyLoQ;
TNimType NTI_eVNY8xahmVtt29cZz5fuKug_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_KzVBdX0o9c9aJpcyeuR3YopA_;

static N_INLINE(void, setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d)(Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t, NF ax, NF ay, NF bx, NF by, NF tx, NF ty) {
	(*t).ax = ax;
	(*t).ay = ay;
	(*t).bx = bx;
	(*t).by = by;
	(*t).tx = tx;
	(*t).ty = ty;
}

N_NIMCALL(Matrix2d_apt8v8Iw9bh7km28IcOJIkg, matrix2d_ZkrhJTvT5qdZLXWIJxuuVw)(NF ax, NF ay, NF bx, NF by, NF tx, NF ty) {
	Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), ax, ay, bx, by, tx, ty);
	return result;
}

static N_INLINE(Point2d_eVNY8xahmVtt29cZz5fuKug, point2d_4HtTb6DBuFYILwb7lqld9agbasic2d)(NF x, NF y) {
	Point2d_eVNY8xahmVtt29cZz5fuKug result;
	result.x = x;
	result.y = y;
	return result;
}

static N_INLINE(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d)(NF x, NF y) {
	Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	result.x = x;
	result.y = y;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void) {
	IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g = matrix2d_ZkrhJTvT5qdZLXWIJxuuVw(1.0000000000000000e+00, 0.0, 0.0, 1.0000000000000000e+00, 0.0, 0.0);
	ORIGO_fcPFYT9cYuzJZVhuTlBCWIA = point2d_4HtTb6DBuFYILwb7lqld9agbasic2d(0.0, 0.0);
	XAXIS_cHisHYvnFnWkQFsXQwR8LA = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(1.0000000000000000e+00, 0.0);
	YAXIS_Tg25xvoRc1btSr7LczyLoQ = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(0.0, 1.0000000000000000e+00);
}

NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void) {
static TNimNode* TM_uZDJJp1iqREI0Whfe9c2S0w_2[2];
static TNimNode* TM_uZDJJp1iqREI0Whfe9c2S0w_3[2];
static TNimNode TM_uZDJJp1iqREI0Whfe9c2S0w_0[6];
NTI_eVNY8xahmVtt29cZz5fuKug_.size = sizeof(Point2d_eVNY8xahmVtt29cZz5fuKug);
NTI_eVNY8xahmVtt29cZz5fuKug_.kind = 18;
NTI_eVNY8xahmVtt29cZz5fuKug_.base = 0;
NTI_eVNY8xahmVtt29cZz5fuKug_.flags = 3;
TM_uZDJJp1iqREI0Whfe9c2S0w_2[0] = &TM_uZDJJp1iqREI0Whfe9c2S0w_0[1];
TM_uZDJJp1iqREI0Whfe9c2S0w_0[1].kind = 1;
TM_uZDJJp1iqREI0Whfe9c2S0w_0[1].offset = offsetof(Point2d_eVNY8xahmVtt29cZz5fuKug, x);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[1].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[1].name = "x";
TM_uZDJJp1iqREI0Whfe9c2S0w_2[1] = &TM_uZDJJp1iqREI0Whfe9c2S0w_0[2];
TM_uZDJJp1iqREI0Whfe9c2S0w_0[2].kind = 1;
TM_uZDJJp1iqREI0Whfe9c2S0w_0[2].offset = offsetof(Point2d_eVNY8xahmVtt29cZz5fuKug, y);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[2].name = "y";
TM_uZDJJp1iqREI0Whfe9c2S0w_0[0].len = 2; TM_uZDJJp1iqREI0Whfe9c2S0w_0[0].kind = 2; TM_uZDJJp1iqREI0Whfe9c2S0w_0[0].sons = &TM_uZDJJp1iqREI0Whfe9c2S0w_2[0];
NTI_eVNY8xahmVtt29cZz5fuKug_.node = &TM_uZDJJp1iqREI0Whfe9c2S0w_0[0];
NTI_KzVBdX0o9c9aJpcyeuR3YopA_.size = sizeof(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA);
NTI_KzVBdX0o9c9aJpcyeuR3YopA_.kind = 18;
NTI_KzVBdX0o9c9aJpcyeuR3YopA_.base = 0;
NTI_KzVBdX0o9c9aJpcyeuR3YopA_.flags = 3;
TM_uZDJJp1iqREI0Whfe9c2S0w_3[0] = &TM_uZDJJp1iqREI0Whfe9c2S0w_0[4];
TM_uZDJJp1iqREI0Whfe9c2S0w_0[4].kind = 1;
TM_uZDJJp1iqREI0Whfe9c2S0w_0[4].offset = offsetof(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, x);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[4].name = "x";
TM_uZDJJp1iqREI0Whfe9c2S0w_3[1] = &TM_uZDJJp1iqREI0Whfe9c2S0w_0[5];
TM_uZDJJp1iqREI0Whfe9c2S0w_0[5].kind = 1;
TM_uZDJJp1iqREI0Whfe9c2S0w_0[5].offset = offsetof(Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, y);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[5].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_uZDJJp1iqREI0Whfe9c2S0w_0[5].name = "y";
TM_uZDJJp1iqREI0Whfe9c2S0w_0[3].len = 2; TM_uZDJJp1iqREI0Whfe9c2S0w_0[3].kind = 2; TM_uZDJJp1iqREI0Whfe9c2S0w_0[3].sons = &TM_uZDJJp1iqREI0Whfe9c2S0w_3[0];
NTI_KzVBdX0o9c9aJpcyeuR3YopA_.node = &TM_uZDJJp1iqREI0Whfe9c2S0w_0[3];
}

